### ISSUE TITLE
shortcut doesn't work

### ISSUE THREAD

**Issue by carlhung** [laurentyhuel/Digital-Photo-Frame-with-Raspberry-Official-Screen#1]
shortcut doesn't work.
when I tap on the shortcut in the menu, I got the following error:
Invalid desktop entry file: '/home/pi/.local/share/applications/fehslideshow.desktop'

**Comment by laurentyhuel** [comment]
What's your linux distribution ?

**Comment by carlhung** [comment]
Raspbian stretch

**Comment by laurentyhuel** [comment]
Add shortcut for Raspian:
45a6c637c5fca74a5bb276d793e8d3931d961305
